embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/builtins/assets/meshes/quad_2x2.dae\"\n"
  "name: \"unnamed\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/lumiere/effects/distortion/apply_distortion.material\"\n"
  "  textures {\n"
  "    sampler: \"input_tex\"\n"
  "    texture: \"/lumiere/transparent.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"distort_tex\"\n"
  "    texture: \"/lumiere/transparent.png\"\n"
  "  }\n"
  "}\n"
  ""
}
