local default_program = require "lumiere.programs.default"
local lumiere = require "lumiere.lumiere"

function init(self)
	lumiere.init()

	lumiere.add_program("default", default_program)
	lumiere.use_program("default")
end

function final(self)
	lumiere.final(self)
end

function update(self)
	lumiere.update(self)
end

function on_message(self, message_id, message)
	lumiere.on_message(self, message_id, message, sender)
end
